### ISSUE TITLE
Firmware 5.3.3 broke EPA AQI Category

### ISSUE THREAD

**Issue by jmwhite5** [bpaauwe/udi-purpleair-poly#4]
I was running 5.3.0 previously and I was getting GV11 fine.  But after upgrading to 5.3.3, GV11 is missing (other values are present).  Not sure if the bug is with this plugin or with the firmware release.

**Comment by bpaauwe** [comment]
I don't see anything in the release notes for 5.3.3 that should effect status displays.  However, 5.3.3 is a test build.

You'll have to check the various logs to verify if the ISY is getting the correct value or not.  The node server log, when set to debug, should show if it's sending an update for GV11.  It should only be sending an update with the value actually changes. Thus, it's possible that if the value hasn't changed since you did the firmware upgrade, no new value would have been sent to the ISY and it would stay blank.  That value will only change on fairly large changes to the PM2.5 value.

**Comment by jmwhite5** [comment]
It started working in the middle of the night.  So I think you are right.  The value hadn’t change until 3am.

**Comment by jmwhite5** [comment]
That being said, I had restarted my cloud polyglot instance, so I wonder what was tracking the previous state, since everything got rebooted.  Isn't there a way to force a refresh?  I tried to hit the "Re-Discover" and "Update Profile" to no avail.

**Comment by bpaauwe** [comment]
Polyglot tracks it. It stores the current value in it's database and checks what the node server sends before forwarding it to the ISY.  This is in place to reduce the load on the ISY as the ISY has limited network resources and will start dropping updates if too many happen at the same time.

It is possible to override this behavior but I'm not doing that in the node server.

Discover simply creates the nodes based on the configuration.  It won't cause the node server to refresh the node values.  The  profiles files are static files on the ISY, so again, won't refresh values.  Because of the ISY's limited network resources, it's also possible for it to silently drop profile files when Polyglot first sends them. If that happens, "Update Profile" allows you to re-send them without re-installing the node server.

**Comment by jmwhite5** [comment]
I see.  So as long as values eventually change, then everything is working as designed.  It would be great if there was a way to force a resync for a scenario like mine, but otherwise this is all working.  Thanks for writing this module by the way.  It's driving  my in-home air purifier.

**Comment by jmwhite5** [comment]
Closing ticket since everything is working as designed.
